### ISSUE TITLE
How a source can "become a portal of the activated document"

### ISSUE THREAD

**Issue by RByers** [WICG/portals#1]
The [carousel example](https://github.com/KenjiBaheux/portals/blob/master/explainer.md#carousel-of-articles-from-different-websites) says:

> The news aggregator becomes a portal of the activated article.
> The activated article would include a provided script to let the news aggregator detect any swipe gestures and communicate to its portal.

But how exactly can the original page ("news aggregator" in this example) "become a portal" in the new active document ("activated article")?  It may have a `WindowProxy` (from a `MessageEvent.source`), but how can the page control the lifetime of that document?  Does just keeping the `WindowProxy` alive keep the original page around?  Can it call `activate()` on something without having to create an actual `<portal>` element?

In an earlier internal proposal I had suggested having an explicit type of object (a "ghost window") for this (which would have the `activate` and `postMessage` methods, as well as some way of being attached to a `<portal>` element). @domenic @ojanvafai you felt such an object was unnecessary, right?  But do we end up with nearly the same thing by having some special type of `WindowProxy` with an `activate` method?

**Comment by KenjiBaheux** [comment]
Great question. 

I think it's handy to have an explicit object for better control over the user experience, unless there are other/better ways to do these:
 - only add a `<portal>` if the destination was loaded in due time or successfully. If we only had the `<portal>` element, wouldn't we end up with empty space / collapsing-triggered-reflows if loading failed or took too long?
 - do a nice fallback if the origin page gets evicted due to memory pressure
 - explictly evict the origin page if the user navigates further away?
 - (TBD) preload the portal destination and its sub-resources before considering attaching it to a `<portal>` and triggering evaluation/rendering work.

**Comment by jeremyroman** [comment]
Most of these points seem, to me, to be orthogonal to the one-object/two-object decision.

I'm in the former camp, primarily because I really don't want "has it been GCed" to be the criteria for cleaning up a portal. To work correctly, I think that requires cross-process GC tracing (else one process can have the dead handle but no GC pressure -- thus no collection, but another process can have the GC pressure but not be able to collect).

Frames deal with the former issue by using attachment of the frame owner element to the document. Not attached, not needed, at the developer's explicit control. (This can be made to work with separate objects, as long as you extend this notion of "explicit ownership from the real frame" through both objects, but it's slightly unnatural.)

I'd imagined something like this:

```js
window.addEventListener('portalactivate', e => {
  let predecessor = e.adoptPredecessor(document);
  console.assert(predecessor instanceof HTMLPortalElement);
  // by special dispensation, this element keeps the portal alive for the duration of the portalactivate event
  // past that, the author must attach it to the document
  document.body.appendChild(predecessor);
});
```

**Comment by KenjiBaheux** [comment]
@ericfs My gut feeling is that the predecessor portal, as @jeremyroman called it, would be the existing instance, not a reloaded version. Otherwise the user experience wouldn't be great on top of state concerns.
