### ISSUE TITLE
Show how portals can be used to create fluid navigation without imposing any specific script

### ISSUE THREAD

**Issue by RByers** [WICG/portals#119]
In [this WICG thread](https://discourse.wicg.io/t/proposal-for-promotable-iframe/2375/22), @triblondon describes a concern with how portals may be used:

> So in this scenario the aggregator persuades/coerces the content creator to include some standard library or piece of markup that is proprietary to that aggregator?

This isn't about portals per se, but about how exactly they can enable the use cases described in this repo. In particular, will portals make it possible to create fluid navigation UX between different origins who agree on nothing but some web standard APIs / protocols?

**Comment by RByers** [comment]
Here's how I'm thinking about it (caveat that this is still early and there are still lots of moving parts and I don't speak for Google as a whole):

The ultimate goal is absolutely to enable two separate origins, which have no shared script or specific knowledge of each other, to have a fluid navigation experience between them. But there's a lot of separate issues to address in the web, all of which must be solved for this to work. So the path by which we get there is somewhat long and has a variety of possible intermediate steps.

One intermediate step I see is that features like the AMP top stories carousel could switch from iframes to portals and signed exchanges to fix the origin problem. But, as Andrew points out, this absolutely does nothing to address the issue of aggregators requiring publishers to rely on particular script they provide. But in my opinion it does provide a convenient testing ground for a key piece of the puzzle.

To achieve the full vision a number of other pieces are needed. For example, we need some standard communication protocol or API so that when a user swipes sideways on a page that has been loaded by such a viewer, the swiping UX the user expects can take over and move to the next/previous site in the list provided by the aggregator. We don't yet have a concrete proposal for what this API should look like, but I think we should figure that out by experimenting with polyfills on top of underlying infrastructure and a few new primitives. We've got a few additional primitives in the works specifically for this, such as an event that fires when swiping past the extent of a scroller, and the ability to hand a scroll gesture off from one page to another as part of a portal transition.

As we get more of the pieces proposed we should update this issue with links to each of the pieces and an end-to-end example so we can discuss openly how all the parts fit together and what the likely implications of their use may be.

**Comment by triblondon** [comment]
> The ultimate goal is absolutely to enable two separate origins, which have no shared script or specific knowledge of each other, to have a fluid navigation experience between them

The use of the word 'enable' here implies that this is something that these origins *want* to do, which is in most cases not true.  The role of a search engine on the web is to find the best content and connect users with it.  Then get out of the way.  There is nothing inherently wrong with the proposal for portals, but my fear is that they are being used to create a new reality in which Google is the web.  Few publishers actually *want* to be consumed as part of a carousel, and few can build a sustainable business doing so.

Consider: I'm not allowed to serve my own AMP content in the carousel (and web packaging will normalise, rather than solve this).  I am not allowed to use an AMP document to show a teaser for a full experience elsewhere.  If I'm a paywalled article, the full text of the article is nonetheless in the DOM prior to authentication, a security vulnerability that Google would never countenance for its own content, yet is allowed to persist for third parties for *years*. 

Here's a web-positive, non-proprietary approach: Any site that publishes a web package within certain reasonable size constraints can appear in a 'top stories' premium search position and be preloaded in a portal.  When the user chooses to navigate to the portal, it is activated, and the search engine result page unloads. No requirement for the content to connect back to the search provider and place itself into a carousel.  To contribute further to good incentives, inclusion in the top stories section could also require a stable first-render.  Developers are capable of working out how to do this without being forced to adopt a prescriptive framework, but need the incentives to do so.  Alex Russell's [never-slow-mode](https://github.com/slightlyoff/never_slow_mode) is another decent example of this.

Finally, syndication has been a thing for many years, and publishers strike deals all the time to make their content available in third party apps and platforms.  For example, the FT (who I used to work for) is available via Bloomberg terminals.  This arrangement did not result in the destruction of a decent portion of the global news industry, showing that it is possible to do this stuff in a collaborative way.

Bottom line: this is not about baking the carousel behaviour into the web platform (which may well kill quality mainstream news for good), but not doing it at all.  While the purpose of portals is to normalise the carousel, I will oppose it.

**Comment by KenjiBaheux** [comment]
> Re: I'm not allowed to serve my own AMP content in the carousel 

What do you mean by "serving my own AMP content"? 
 - You did make the content available. It's yours.
 - Are you upset about not being able to serve the bytes directly? As a publisher? Why?


> (and web packaging will normalise, rather than solve this). 

If anything Web Packaging will  actually get closer to what you want, you will get ownership of the content (integrity and authenticity). I'm rather surprised that you reach this negative conclusion about web packaging despite having recommended it in the [past](https://www.w3.org/2001/tag/doc/distributed-content/#recommendations). What has changed?


> I am not allowed to use an AMP document to show a teaser for a full experience elsewhere. 
Is this a documented AMP practice? It's not something we can fix at the platform level. I recommend filing an issue against AMP.


> If I'm a paywalled article, the full text of the article is nonetheless in the DOM prior to authentication
As far as I can tell progress is being made on a [relevant issue](https://github.com/ampproject/amphtml/issues/21658). This is also an AMP issue, not a platform issue.

Re these AMP specific issues, we are definitely aiming at allowing non AMP content to participate. If getting traction on these AMP issues isn't going well, there will be room for alternatives.


>Bottom line: this is not about baking the carousel behaviour into the web platform (which may well kill quality mainstream news for good), but not doing it at all. 

Portals is not about baking the carousel. In 2 years from now we will all look at the carousel as an obsolete UX pattern :D.

Please explain how a carousel could kill quality mainstream news for good, this is a pretty strong statement to make. If we are being honest here, most users consume their news via native apps who do offer far more fancier UX. The carousel has been around for a while too. Are there measurable sign of a correlation between these UX and the quality of mainstream news?


>While the purpose of portals is to normalise the carousel, I will oppose it.
We can leave the web behind in terms of user experience and let native continue to eat everything with proprietary formats that no longer live on the web. Is that a good outcome?

**Comment by twifkak** [comment]
@triblondon, I'm confused by the negative connotation behind your use of the word "normalise". AFAICT, normalising common practices is the most important role of SDOs. Doing so enables interoperability between all end points and intermediaries. This, in turn, enables greater choice and greater control - for all people. For instance, if search engines adopt web packaging and portals for their carousel UIs, this enables:

 - non-AMP in carousels
 - web packages that are compatible with all aggregators
 - UA intervention of page transitions (whereas now, iframe fullscreen intent can only be heuristically determined)

Your concern seems predicated on the notion that portals are a precondition for the continued prevalence of carousel UIs, and I see no evidence of that.

**Comment by triblondon** [comment]
> Are you upset about not being able to serve the bytes directly? As a publisher? Why?

Because that's how the web works.  Google is using a dominant market position to coerce me into having you serve my website.  I don't want to do that.  Similarly, Uber has a great UX, so why don't cities get rid of their expensive taxi licensing schemes and just let Uber run the whole system?

> Is this a documented AMP practice? It's not something we can fix at the platform level. I recommend filing an issue against AMP.

Filing an issue has historically not proven to be an effective way to change Google's business strategy.

> progress is being made

Meanwhile, multiple newsroom closures per week.  The situation has become especially dire in the last few months which is why I'm trying to put this as plainly as possible.

> We can leave the web behind in terms of user experience and let native continue to eat everything with proprietary formats

I don't see why this is a problem.  Native is not the web, if people want to use it, fine.  I don't see why we want to turn one into the other.

> Your concern seems predicated on the notion that portals are a precondition for the continued prevalence of carousel UIs, and I see no evidence of that.

They normalise that behaviour, in particular via the 'adoption' mechanism.  Without portals, there is an argument that AMP is a hack (which of course it is).  With portals, you can reasonably claim that the web platform has explicit support for this kind of behaviour.

I don't think I've made the case strongly enough in this thread so I explained in greater length in a blog:
https://trib.tv/2019/05/28/cake-or-death-amp-and-the-worrying-power-dynamics-of-the-web/

Worth saying by the way that news sites in general have been rubbish at perf and a cesspit of 3rd party trackers.  An intervention is definitely warranted.  AMP is not the right intervention, so Portals need to have this AMP-enabling feature (orphaning/adoption) removed.

**Comment by matthewp** [comment]
Portals are not just for AMP. I want to use portals to build fluid navigation between pages within my own domain.

It's a shame to me that AMP has sort of hijacked 2 interesting ideas now; portals and webpackages. On their own they are a good idea that solves problems developers experience every day. I think we should continue to debate the features that AMP wants in these proposals without blocking them for the more simple uses.

**Comment by KenjiBaheux** [comment]
Given that the concerns expressed here are not technical, I'm closing this issue. It doesn't mean that we are disregarding the feedback.

Matthewp: rest assured that you are not alone, we are seeing tremendous interest in these features for a wide variety of use cases. We will keep moving forward and listening to developers and implementers for directly related feedback or concerns to inform the design of these APIs.

How players might use these features is a separate matter. The same discussion could have been had about iframes given that's what AMP is using today. But, it's a key part of the web with net positive impact. The same argument applies to other APIs already part of the web platform or being worked on.

Andrew: Ignoring the bombastic cause-effect claim, your blog post does identify the root issue which myself and many other team members are interested in: helping the publishing industry adapt to a rapidly changing environment, identify mutually beneficial opportunities, etc. I've heard echoes of interest in this topic from other folks in the community. It's a hard problem but it's the one that's worth spending our energy on.

**Comment by tobie** [comment]
Putting aside for a minute the deeper and critically important concerns about the sustainability of the press expressed by @triblondon, it seems that the issue brought-up in the OP—how to enable navigations from different origins without requiring these to include a script—is still relevant.

@RByers [mentioned](https://github.com/WICG/portals/issues/119#issuecomment-491432488)  that enabling this was the plan, outlined a tentative roadmap for doing so, and suggested to "update this issue with links to each of the pieces and an end-to-end example so we can discuss openly how all the parts fit together and what the likely implications of their use may be."

I think this is still a worthwhile conversation to have, and this issue looks like the appropriate venue for it. Maybe the broader conversation about press sustainability could be moved elsewhere (possibly even to a different forum), and maybe we could also open a separate issue on the topic of the orphaning/adoption mechanism of portals itself, which is distinct from this one.

**Comment by KenjiBaheux** [comment]
I agree that it would be worthwhile. Given that the trigger for that particular discussion was an AMP related concern, it seems like a better fit would be an AMP related repo. I believe that there was a meta list of APIs/Projects in one of the AMP Project repos about [the plan](https://blog.amp.dev/2018/03/08/standardizing-lessons-learned-from-amp/), perhaps that's an option.

Any suggestion about where to keep discussing the press sustainability issue?

**Comment by twifkak** [comment]
I believe this is the [meta list](https://github.com/ampproject/amphtml/blob/master/contributing/web-standards-related-to-amp.md) you're referring to.
