### ISSUE TITLE
Accessing portal's window and/or document prior to activation

### ISSUE THREAD

**Issue by gclevin** [WICG/portals#179]
Is there a way to access a portal's window and/or document prior to activation similar to the way you can access an iframe's `contentDocument` or `contentWindow`?

**Comment by a4sriniv** [comment]
No there isn't, currently `postMessage` is the only way for a portal embedder to communicate with the portal before activation.

**Comment by jeremyroman** [comment]
We would also prefer not to add `contentDocument` or `contentWindow` in the future; this was an intentional decision on our part.

It would limit implementations from hosting the document on another thread of execution or process (which implementations might wish to do for security or performance reasons), and make some likely future directions (such as freezing or discarding portal contents by either the UA or the author) substantially more difficult.
