### ISSUE TITLE
Styling hooks while portaled

### ISSUE THREAD

**Issue by bokand** [WICG/portals#241]
This is closely related to #173 - it seems  likely the model we want is a replaced-like model, where the portaled page is rendered with its initial containing block matching the outer viewport size. This will ensure that sizing isn't a communication channel between the embedder and embeddee and that activation is seamless without a big relayout (and also, most content probably isn't well suited to be rendered in small boxes or may switch to a mobile layout).

However, as @domenic mentions - this model would commonly result in a poor preview. I think this invites three questions:

1. What should the default be?
2. What styling hooks should the embedder have, if any?
3. What styling hooks should the embeddee have? How should these interact with those in the second point?

#### 1. What should the default be?

If embedder just dumps a stock `<portal>` to an unexpecting page, how should it be rendered? IMHO, just scaling the page down using the equivalent of `object-fit: contain; object-position: top` should look ok (if too small) in most cases. This would look similar to Domenic's [first example](https://github.com/WICG/portals/issues/173#issuecomment-625457227-permalink:~:text=I%20guess%20both%3A)

#### 2. What styling hooks should the embedder have, if any?

If the target page doesn't expect to be portaled, the embedder could put in some effort to make the portal look more appealing. E.g. by changing `object-fit` and `object-position` to fill the portal with the most relevant content. It looks like `object-fit` doesn't today allow arbitrarily "zooming in" - limiting what an embedder could do but for the sake of argument, assume the embedder could choose the exact rect of the rendered page to use as a preview (in some other way).

It's not clear to me embedders should have this ability - destination pages may not want to give up this control for a number of reasons: brand control, editorialized previews, hiding information, etc.

It definitely seems like _embedees_ should be able to control how their pages are previewed - but, if embedders can also add some customization, what happens if the destination page makes some changes and breaks the outer customizations?

#### 3. What styling hooks should the embeddee have? How should these interact with those in the second point?

Interaction with the above would be easiest if there was no way for the embedder to modify the portal preview and this would be my preference.

OTOH, maybe it's useful enough that we need to allow it; in that case, I think an embeddee provided preview should override the choices of the embedder, rather than try to combine them. Otherwise, when adding/modifying their previews, embeddees would have to anticipate all the choices embedders might have made which they can't realistically account for.

On the mechanism:

I think this fits nicely with media queries:

```
@media (render-mode: preview) {
  #logo {
    position: fixed;
    width: 100%; height: 50%;
    left: 0; top: 0;
  }
  #title {
    position: fixed;
    width: 100%; height: 50%;
    left: 0; top: 50%;
  }
}
```

Given the default of `object-fit: contain; object-position: top` the embeddee will always know how the preview will look, only the size may change. This seems to me like a reasonable amount of richness without adding a ton of complexity.

What do y'all think?

**Comment by jeremyroman** [comment]
`object-fit` + `object-position` do let you zoom/pan as long as the zoom you want is 100% of original size, with `object-fit: none`. Obviously for 3P cases you might not know where to zoom to.

Defaulting to `object-fit: contain` makes sense to me mostly because I think stretching the preview (or any replaced content, honestly) looks silly. I don't follow the argument for `object-position: top`, though; this just affects the alignment of the preview inside the embedder-provided box, which feels like it's very reasonably inside their control (and so I'd have expected the default to be `50% 50%` as usual).

It sounds like you might be proposing to restrict the legal values of `object-fit` to restrict embedder clipping, though it's not clear to me this really prevents much, as the embedder can still clip the preview by putting it in another element and applying `clip` or `overflow: hidden`.

The last question sounds like a dupe of #3; a media query may well be useful -- perhaps moreso now that we expect scaling to make the author's content tiny in the common case, giving them more reason to adjust style in this mode. If you want to pursue that now you should probably take over that issue (or merge it with this one, considering they have basically the same name anyhow).

One would hope authors who did this would also add some sort of nice transition to keep this seamless; it's probably not great for seamlessness if authors make radical changes to their style/layout without smoothly transitioning. But not much we can do about that.

The other question, though, is whether authors should make their logo/title/etc huge while in a portal. If the portal is tiny, then it makes sense, but if the portal is at or close to 100% scale, as in a swipe-from-bottom or fullscreen carousel experience, then making those style changes is probably actually negative for user experience in many cases. It's difficult to figure out how we could distinguish the two without providing too useful a communication channel. Maybe a bit that says "scale was >50% when the portal element load started" is safe even if we can't provide the exact scale all the time, or something like that? Alternatively, we could punt on this and see what becomes more common in experimental or real usage.

**Comment by bokand** [comment]
>  I don't follow the argument for object-position: top

Oops, that's a remenant from when I was toying with making the default `object-fit: cover`. Agree leaving it as the usual `50% 50%` default makes more sense with `contain`.

> It sounds like you might be proposing to restrict the legal values of object-fit to restrict embedder clipping, though it's not clear to me this really prevents much, as the embedder can still clip the preview by putting it in another element and applying clip or overflow: hidden.

Yup, I hadn't thought of this at the time - given that, I agree there's no sense in restricting it.

> The last question sounds like a dupe of #3;

Ah, hadn't seen it - I'll close this in favor of it.

> making those style changes is probably actually negative for user experience in many cases. It's difficult to figure out how we could distinguish the two without providing too useful a communication channel

Yeah, I think we could provide some kind of low-granularity size information (e.g. 200px increments) and only populate it during load (i.e. resizes aren't communicated). That seems like it'd remove resize as a communication channel; though pages could still remove/re-add a portal and use the size to communicate info. I'm not sure that's an issue since the outer page could also use ordered resource fetches to the same server to communicate similarly.

In any case, I think as long as we have some vaguely plausible path visible to us for how this might work I'm of the mind that we can punt on this for now.

**Comment by domenic** [comment]
> 1. What should the default be?

I agree that scaling it down seems reasonable.

> 2. What styling hooks should the embedder have, if any?

> If the target page doesn't expect to be portaled...

This should not be possible. The plan is that content needs to opt-in to being portaled. So, I don't think we need to give embedders much control. And as you say over in #173, they can get some basic control over the experience (but not the rendering) by just slapping an image over the top of the portal or similar.

> 3. What styling hooks should the embeddee have? How should these interact with those in the second point?
>
> I think this fits nicely with media queries:

I'm not a CSS expert, but I generally agree. I'll move this discussion over to there.
