### ISSUE TITLE
Why does adoptPredecessor() take a document?

### ISSUE THREAD

**Issue by domenic** [WICG/portals#30]
I guess theoretically you could pass a same-origin iframe or window.open()ed document to it, but when is that a good idea? Perhaps just always use, or at least default to, the current settings object's responsible document?

**Comment by jeremyroman** [comment]
Mostly just intended to follow other APIs which create elements; e.g. the constructors all internally take a document, and authors write document.createElement('div') rather than "new HTMLDivElement()". I'm not opposed to removing this, and possibly adding it back later in an options dictionary if we find it necessary.

The other option, incidentally, would be to require the author to create the HTMLPortalElement for us, and make the API take that portal element (which I suppose could also have the advantage that you could already have made room for it in the layout, and so avoid needing to reflow as part of adoption). The choice we initially made was fairly arbitrary; what do you think the right API shape here is?

**Comment by domenic** [comment]
It's a fair point that this behaves kind of like an element-creation API; I hadn't thought of that. That said, we would like to add constructors one day that do use the implicit document. I would lean toward making it optional for now.

I like the adoptPredecessor() API shape, although there might be better naming options. (For example it's not obvious that it's creating a new portal element. But, I have no suggestions that don't get super-verbose.) I think having authors create the element in an inert, intermediate state, only to have another function twiddle with its internals to make it useful, would be weirder.

**Comment by jeremyroman** [comment]
Fixed in 6e1843d5ec32186c88a2781ff2966fa4738c934f.
