### ISSUE TITLE
"The user agent should not refuse to allow the document to be unloaded."

### ISSUE THREAD

**Issue by domenic** [WICG/portals#68]
It's not clear what the intention is here. My most literal reading is that the UA should proceed with all the steps of https://html.spec.whatwg.org/multipage/browsing-the-web.html#prompt-to-unload-a-document, but then even if the user clicks "No don't unload", ignore what the user says.

It seems like a better experience to recommend would be to avoid asking the user entirely. In that case, the operative sentence you want to influence from the "prompt to unload" algorithm is

> then the user agent may ask the user to confirm that they wish to unload the document.

I recognize there is no nice dfn to link to there, but just saying "While executing the [prompt to unload] algorithm, the user agent should not ask the user to confirm that they wish to unload the document" seems good to me.

We could try to make this even more precise, such as adding a flag which we thread all the way through from the "close" algorithm to that "prompt to unload" step. But as long as it stays a "should" that overrides a "may", I think that level of explicitness is not necessary. If we wanted it to be a "must", I'd reconsider.

**Comment by jeremyroman** [comment]
Looking at this more closely, I wonder whether we should actually be running the "close" algorithm in all of these cases, or whether some of them should "discard" (for instance, [`<iframe>` does discard if you remove it from the DOM](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element:a-browsing-context-is-discarded)).

Is there a unifying philosophy about when we should "close" (and fire `unload`) vs "discard" (and not)?

**Comment by domenic** [comment]
Good catch. It looks like "close" is used for top-level BCs only, when the user clicks the close button, or when script does `window.close()` on a popup that it previously created.

To be clear, the difference is that closing will do a bunch more work:

- Prompt to unload (beforeunload events, recursively)
- Unload (pagehide + unload events, recursively)

I wonder if we want to use portals as an opportunity to address some legacy mistakes here. I know beforeunload is generally deprecated and unreliable; we could skip that, at least.

Maybe stepping back, where is "close" used in portals? https://pr-preview.s3.amazonaws.com/jeremyroman/portals/pull/131.html seems to indicate:

- Via "set the source URL", either on becoming BC-connected, or changing src="".
- During activation, the predecessor gets closed.

IMO "set the source URL" discarding would feel more consistent. We probably shouldn't change the predecessor getting closed though?

**Comment by jeremyroman** [comment]
AFAICT, iframes *do* dispatch `beforeunload` and `unload` when you set their `src` (similarly to how it would behave if you navigated within the BC otherwise, e.g. by clicking a link). That's why I leaned toward using "close" instead of "discard" there.

**Comment by domenic** [comment]
Ah yeah, you're right, it performs a navigation that will automatically end up doing prompt to unload, then "update the session history" which does a bunch more stuff. Interesting. So maybe the close step there is actually redundant entirely?

**Comment by jeremyroman** [comment]
So there's presently a small difference in how we deal with empty or invalid URLs. `<iframe>` changes the URL to `about:blank` and navigates to that (and, I believe, also does so if you attach it without first setting a `src`); `<portal>` currently dumps the BC altogether.

The logic behind that decision was that when you activate a portal we can't simply navigate its guest BC to `about:blank`, because the BC is still in use – in fact, it has become a tab! So in that case we need either immediately make a fresh BC to go to `about:blank` (which seems wasteful, since in practice a just-activated portal is reasonably likely to be removed or replaced shortly thereafter), or make `<portal>` support an "inert" state in which it has a null guest BC. This state also proves useful for cases where we don't want to let you use portals, like in a nested BC.

Given that such a state exists, it seemed reasonable that clearing src and removal from the DOM would both create that state. Another reasonable option is something closer to iframe behavior, which navigates to `about:blank` if src is empty or invalid. (To do so I'll need to quickly revise a recent change we made, to make it legal to go to `about:blank` as well as HTTP(S) URLs, but that's doable.) It would be more consistent with iframes, I suppose. Do we then have to worry about special behavior of the "initial `about:blank`" then, though?

**Comment by domenic** [comment]
I follow that reasoning now! I like the idea of removing the special initial about:blank, and using no-BC as the invalid state. I think just noting that in the spec would be good. Something like

> Note: unlike iframes, portals do not navigate to about:blank to signal an error state. Instead, error states result in the guest browsing context being closed. Similarly, portals do not have a special initial about:blank page from which the first navigation always happens with replacement enabled; instead, they load the URL given by their src="" attribute directly.

I still am unsure between discard and close for error states. (Or even a third option, like close-but-no-beforeunload event.) I think we should pick one (I guess you are leaning toward close), then open a new issue that extracts and summarizes the relevant parts of this thread, for broader discussion.

**Comment by jeremyroman** [comment]
I am, mostly because currently we would also fire `beforeunload` and `unload` when setting src to a valid non-empty URL, so it seems most parallel.

**Comment by jeremyroman** [comment]
Added such a [note](https://github.com/WICG/portals/pull/131/commits/a652ca35cd37409c576ab8797c1dd8d1860c1f5e).
