### ISSUE TITLE
Unclear what "complete portal activation" vs. "set the portal state" note is referring to

### ISSUE THREAD

**Issue by domenic** [WICG/portals#70]
> Since the task to set the portal state, and thus expose the PortalHost object, is queued before the task to complete portal activation, from the same task source, it is exposed at the time the promise returned from activate() is resolved. 

I can't find any algorithm which both sets the portal state and calls "complete portal activation".

My best guess is that this is referring to a specific user code workflow that calls adoptPredecessor() from the activate event. If so it'd be best to include that code example explicitly. If that's not it though, I'm lost.

**Comment by jeremyroman** [comment]
This has since been reworded (as part of pull #127) to read:

> Since the task to set the portal state, and thus expose the PortalHost object, is queued first, and from the same task source, it is exposed at the time the promise returned from activate() is resolved.

It refers to the task above it in the [**adopt the predecessor browsing context**](https://wicg.github.io/portals/#adopt-the-predecessor-browsing-context) steps, and the logic in the [`adoptPrecessor` operation](https://wicg.github.io/portals/#dom-portalactivateevent-adoptpredecessor) to resolve the [activation promise](https://wicg.github.io/portals/#portalactivateevent-activation-promise).

Is it now clear, or would you like further clarification?

**Comment by domenic** [comment]
I think this would still benefit from a code example. It seems it is referring to a specific scenario where user code calls both activate() and adoptPredecessor(); showing that scenario in code would help.
