### ISSUE TITLE
IDL tweaks for post messaging

### ISSUE THREAD

**Issue by domenic** [WICG/portals#74]
```webidl
dictionary PortalActivateOptions {
    any data = null;
    sequence<object> transfer = [];
};
```

I think this would be better as

```webidl
dictionary PortalActivateOptions : PostMessageOptions {
    any data;
};
```

(the normative difference being that the default is undefined instead of null.)

Separately I considered whether `message` or `data` was better, but I concluded matching the web-dev-visible property name on `MessageEvent` was more important than matching the non-visible spec name for the parameter to postMessage.

**Comment by jeremyroman** [comment]
Is extending PostMessageOptions to get its one member worth it? Especially since I'm not sure how it will be extended, so it wasn't obvious to me whether we would want to automatically get whatever future options are added.

I don't remember any strong reason for preferring `null` vs `undefined` (though my time working on the serializer made me recall that Blink/WebKit have historically used `null` for a variety of cases where we couldn't deserialize a message). The theory here I assume is that this is similar to writing `postMessage()` (because omitted arguments are `undefined` in JS)?

**Comment by jeremyroman** [comment]
(man, GitHub issues and PRs look so similar; I can move this comment there if you'd prefer)

**Comment by domenic** [comment]
> Is extending PostMessageOptions to get its one member worth it? Especially since I'm not sure how it will be extended, so it wasn't obvious to me whether we would want to automatically get whatever future options are added.

Well, it's currently used or extended by all the other APIs on the platform, so it seems like the right fit to me. I'd be surprised if we extended it with something that didn't make sense in all those cases.

> The theory here I assume is that this is similar to writing postMessage() (because omitted arguments are undefined in JS)?

Pretty much, yeah. In particular writing `activate({})` should be the same as writing `activate({ data: undefined })`. With the current spec the former is actually equivalent to `activate({ data: null })`.

**Comment by jeremyroman** [comment]
the other likely thing is that PostMessageOptions in Chromium is WindowPostMessageOptions in the spec which has stuff that isn't appropriate here . . . we should fix that
